### ISSUE TITLE
TypeScript & React - Sample code fails to build

### ISSUE THREAD

**Issue by ManuLEM** [InVisionApp/dsm-storybook-cli#11]
I have followed all the instructions in order to be able to publish my DSM using storybook. I have stories with actions and Knobs that work and display the component properly. Here is an example of one of them:
```
<ApButton
    clickCallback={action('button-click')}
    disabled={boolean('Disabled', false)}
    variant={radios('Variant', variantOptions, 'contained')}
    className={radios('state', classes, '')}
>
    {text('Text', 'Button')}
</ApButton>
```
However, my components' sample code still return "Failed to build sample code. Please contact support@invisionapp.com."

When taking a closer look, I saw that my console would return a `Cannot read property 'name' of undefined` error (as an info, btw), from a minified file. So, after cloning your repo and debugging, I figured that the error came from the file `src/sample-code-generation/build-sample-code-utils.js` on line 41:
```
const defaultValueString = getDefaultValueString(prop.type.name, prop.defaultValue.value);
```
At this point, you try to send `prop.type.name` without checking if `prop` and `prop.type` exist before. The thing that I noticed is that I do not have any `type` in my prop, leading to the error above.

I do not know where this type is supposed to come from as, as far as I can tell, this object is generated by the `getStory()` in the `with-dsm` file (I might be wrong about that one).

Now, in order to get the behavior I want, I ended up changing line 41 of `src/sample-code-generation/build-sample-code-utils.js` to  turn it into:
```
const defaultValueString = getDefaultValueString((prop.type && prop.type.name) || 'any', prop.defaultValue.value);
```
This way, other types are still handled the same way, and if none is given, it resorts to using the fallback, not crash.

This modification gets the job done for me, but as I do not have the whole picture, I figured you might come up with a better fix.

Cheers!

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
