### ISSUE TITLE
Update documentation to include setting authToken via DSM_AUTH_TOKEN environment variable

### ISSUE THREAD

**Issue by wrightnathan** [InVisionApp/dsm-storybook-cli#16]
I was trying to find a way to publish to DSM during my app's automated build process without exposing the authToken in plain text.  I found the following code which appears to allow setting it via the DSM_AUTH_TOKEN environment variable:

https://github.com/InVisionApp/dsm-storybook-cli/blob/fb6c9e4c2bf3755dbcfd61c5c4e1e371172f65e3/src/cli/build-configuration.js#L72

I couldn't find any mention of this in the [configuration documentation](https://support.invisionapp.com/hc/en-us/articles/360028510211).  It would be nice to add it there.

**Comment by YoungElPaso** [comment]
Ah! Thanks so much for filing this issue! I didn't find that information either and also require it. Instructions saying to paste the token right into the dsmrc file doesn't seem like the most secure way to handle this.

Be great if this was documented.

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
