### ISSUE TITLE
Scripts not running due to new vue version

### ISSUE THREAD

**Issue by andabarle** [InVisionApp/dsm-storybook-cli#2]
Running either dsm-storybook publish or preview (with fresh dependency install) will throw the error:

```
Vue packages version mismatch:
- vue@2.6.11 (.../node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (.../node_modules/vue-template-compiler/package.json)
```

Both vue and vue-template-compiler were bumped to version 2.6.11 on 13 Dec 2019.

**Comment by mortal94** [comment]
Hey @andabarle ! thank you for notifying us. we've deployed version `0.0.120` of `@invisionapp/dsm-storybook` which addresses this issue.

**Comment by andabarle** [comment]
Awesome! Thank you, @mortal94

**Comment by justdanallen** [comment]
I'm getting this same error on: ` "@invisionapp/dsm-storybook": "0.0.126"`

We are using react components, not vue.

```
Error: 

Vue packages version mismatch:

- vue@2.6.11 (/Users/dan.allen@getweave.com/Weave/platform-ui-components/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/dan.allen@getweave.com/Weave/platform-ui-components/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

**Comment by plmok61** [comment]
@andabarle We are having the same issue as justdanallen. We are not using Vue at all in our project. We use React

**Comment by plmok61** [comment]
@justdanallen as a workaround I installed `vue-template-compiler@2.6.11`. We are not using Vue but this solved the issue.

**Comment by justdanallen** [comment]
@plmok61 Thanks for the tip! Fixed it for me as well. 

@ByronGuina please fix this sometime.

**Comment by adam-zhu** [comment]
```
Error: 

Vue packages version mismatch:

- vue@2.6.11 (/Users/adamzhu/Bright/lumen/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.12 (/Users/adamzhu/Bright/lumen/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
``

I am seeing this issue crop up again with these versions:
```
    "@invisionapp/dsm-storybook": "0.0.131",
    "@storybook/addon-a11y": "^5.3.21",
    "@storybook/addon-actions": "^5.3.21",
    "@storybook/addon-centered": "^5.3.21",
    "@storybook/addon-docs": "^5.3.21",
    "@storybook/addon-info": "^5.3.21",
    "@storybook/addon-knobs": "^5.3.21",
    "@storybook/addon-links": "^5.3.21",
    "@storybook/addon-options": "^5.3.21",
    "@storybook/addon-storysource": "^5.3.21",
    "@storybook/addon-viewport": "^5.3.21",
    "@storybook/addons": "^5.3.21",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/preset-typescript": "^3.0.0",
    "@storybook/react": "^5.3.21",
```
What resolved it was moving down the dsm version. `"@invisionapp/dsm-storybook": "0.0.130"`

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
