### ISSUE TITLE
Support declarative configuration breaks storybook

### ISSUE THREAD

**Issue by kubal5003** [InVisionApp/dsm-storybook-cli#29]
The[ pull request ](https://github.com/InVisionApp/dsm-storybook-cli/pull/25) broke storybook for me.
It won't even open with an exception:
`Uncaught SyntaxError: Unexpected token u in JSON at position 0`

The code that is generated from `register.js` file is as follows:
![image](https://user-images.githubusercontent.com/1132035/93201741-e4b99280-f751-11ea-9f02-8ba11c914ffa.png)

Parsing an Object throws the exception I mentioned above.
Please either fix this issue or rollback those changes.

In the Storybook+DSM integration guide you also mention to always install the latest version in package.json like so:
`"@invisionapp/dsm-storybook": "latest",`

I think that in light of that kind of bug it might make sense to rethink that approach.

CC: @ByronGuina

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
