### ISSUE TITLE
Compatibilities with new add on controls

### ISSUE THREAD

**Issue by legarsjules** [InVisionApp/dsm-storybook-cli#33]
I know that the sample code generator is based on knobs addon, this addon will be deprecated in the next major release of storybook. The new addon controls will replace it, it is already possible to use it instead of knobs. 
Is it plan to update the dsm cli to be able to use controls instead of old knobs ?

Thanks

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
