### ISSUE TITLE
Error running preview command when project path contains a space

### ISSUE THREAD

**Issue by ruckefeller** [InVisionApp/dsm-storybook-cli#34]
Steps to reproduce:
Download the dsm storybook example library.
Unzip and open the angular folder.
Rename the `storybook-v6` folder to `storybook -v6` (or just put a space anywhere in the folder path).
Open `storybook -v6` folder
npm install.
Run `dsm-storybook:preview`
Observe error.

Operating system: Windows 10 x64.

![image](https://user-images.githubusercontent.com/13913210/101391425-e646b280-3889-11eb-9e6b-010600cab42f.png)

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
