### ISSUE TITLE
SSRF vulnerability reported with axios dependency

### ISSUE THREAD

**Issue by australianfrog** [InVisionApp/dsm-storybook-cli#38]
I just wanted to report that the `axios@0.19.0` dependency should be updated due to SSRF vulnerability report https://www.npmjs.com/advisories/1594

Cheers

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
