### ISSUE TITLE
Integrating @storybook/html in DSM - displays loading

### ISSUE THREAD

**Issue by mahathikrishna** [InVisionApp/dsm-storybook-cli#6]
After publishing HTML storybook to DSM, I see "Loading..." but the storybook does not load. 

![image](https://user-images.githubusercontent.com/9600293/73393067-aa71b280-42a0-11ea-9f35-472c48cbb4af.png)

**package.json**

```
"scripts": {
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook -c .storybook -o .out",
    "deploy-storybook": "storybook-to-ghpages",
    "dsm-storybook:publish": "dsm-storybook publish",
    "dsm-storybook:preview": "dsm-storybook preview"
  },
  "dependencies": {
    "@invisionapp/dsm-storybook": "latest",
    "npm": "^6.13.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@storybook/addon-a11y": "^5.3.9",
    "@storybook/addon-actions": "^5.3.9",
    "@storybook/addon-backgrounds": "^5.3.9",
    "@storybook/addon-centered": "^5.3.9",
    "@storybook/addon-docs": "^5.3.9",
    "@storybook/addon-knobs": "^5.3.8",
    "@storybook/addon-options": "^5.3.9",
    "@storybook/addons": "^5.3.9",
    "@storybook/html": "^5.3.2",
    "@storybook/storybook-deployer": "^2.8.1",
    "babel-loader": "^8.0.6",
    "babel-runtime": "^6.26.0",
    "eslint": "^6.8.0",
    "jquery": "3.4.1"
  },
```

**config.js**
```
import { configure, addDecorator, addParameters } from '@storybook/html';
import { withA11y } from '@storybook/addon-a11y';
import centered from '@storybook/addon-centered/html';
import { initDsm } from '@invisionapp/dsm-storybook';


addParameters({
  backgrounds: [{ name: 'DSM background', value: '#f8f8fa', default: true }, { name: 'dark', value: '#333' }]
});

addParameters({ docs: { page: null } });
addDecorator(withA11y);
addDecorator(centered);

//Init Dsm
initDsm({
  addDecorator,
  addParameters,
  callback: () => {
    // apply the custom options
    // setCustomOptions();
    configure(require.context('../stories', true, /\.stories\.js$/), module);
  }
});
```

**Comment by mahathikrishna** [comment]
> After publishing HTML storybook to DSM, I see "Loading..." but the storybook does not load.
> 
> ![image](https://user-images.githubusercontent.com/9600293/73393067-aa71b280-42a0-11ea-9f35-472c48cbb4af.png)
> 
> **package.json**
> 
> ```
> "scripts": {
>     "storybook": "start-storybook -p 6006",
>     "build-storybook": "build-storybook -c .storybook -o .out",
>     "deploy-storybook": "storybook-to-ghpages",
>     "dsm-storybook:publish": "dsm-storybook publish",
>     "dsm-storybook:preview": "dsm-storybook preview"
>   },
>   "dependencies": {
>     "@invisionapp/dsm-storybook": "latest",
>     "npm": "^6.13.7"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.8.0",
>     "@storybook/addon-a11y": "^5.3.9",
>     "@storybook/addon-actions": "^5.3.9",
>     "@storybook/addon-backgrounds": "^5.3.9",
>     "@storybook/addon-centered": "^5.3.9",
>     "@storybook/addon-docs": "^5.3.9",
>     "@storybook/addon-knobs": "^5.3.8",
>     "@storybook/addon-options": "^5.3.9",
>     "@storybook/addons": "^5.3.9",
>     "@storybook/html": "^5.3.2",
>     "@storybook/storybook-deployer": "^2.8.1",
>     "babel-loader": "^8.0.6",
>     "babel-runtime": "^6.26.0",
>     "eslint": "^6.8.0",
>     "jquery": "3.4.1"
>   },
> ```
> 
> **config.js**
> 
> ```
> import { configure, addDecorator, addParameters } from '@storybook/html';
> import { withA11y } from '@storybook/addon-a11y';
> import centered from '@storybook/addon-centered/html';
> import { initDsm } from '@invisionapp/dsm-storybook';
> 
> 
> addParameters({
>   backgrounds: [{ name: 'DSM background', value: '#f8f8fa', default: true }, { name: 'dark', value: '#333' }]
> });
> 
> addParameters({ docs: { page: null } });
> addDecorator(withA11y);
> addDecorator(centered);
> 
> //Init Dsm
> initDsm({
>   addDecorator,
>   addParameters,
>   callback: () => {
>     // apply the custom options
>     // setCustomOptions();
>     configure(require.context('../stories', true, /\.stories\.js$/), module);
>   }
> });
> ```

Downgrading to V5.2.1 works. Not sure why 5.3.9 doesnt work with the integration

**Comment by mortal94** [comment]
Hey @mahathikrishna , thanks for reporting this! We will take a look and get back to you.

**Comment by ByronGuina** [comment]
Hey @mahathikrishna 👋. Can you show us the code for the `addons.js` and **Badge** component you are trying view in DSM? You can remove the `in-dsm` object from the **Badge** code.

**Comment by mahathikrishna** [comment]
Absolutely @ByronGuina 

**addons.js**

```
import '@storybook/addon-knobs/register';
import '@storybook/addon-actions/register';
import '@storybook/addon-a11y/register';
import '@storybook/addon-backgrounds/register';
import { registerDsm } from '@invisionapp/dsm-storybook/register';

registerDsm(process.env.STORYBOOK_DSM);
```

badge.stories.js

```
storiesOf("Components|Atoms/Badge", module)
  .addDecorator(centered)
  .add("BadgeVariation", () => BadgeVariation, {
    'in-dsm': {
      id: 
    }
  });
```

The `BadgeVariation `is just an HTML import file

**Comment by ByronGuina** [comment]
Thanks @mahathikrishna! We'll continue looking into it.

Another question: Are you able to run `dsm-storybook preview` and run the `dsm-storybook` addon locally? Do you get any errors running it locally on Storybook 5.3.9?

**Comment by yec** [comment]
Having the same problem. The storybook is there if i change the opacity of class .c-storybook-tab to 1. or add .loaded class.
<img width="1033" alt="Screen Shot 2020-03-08 at 1 25 56 am" src="https://user-images.githubusercontent.com/210309/76145223-d112dc80-60db-11ea-99ac-5462e53cddf7.png">

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
