### ISSUE TITLE
Monorepo setup?

### ISSUE THREAD

**Issue by MMT-LD** [InVisionApp/dsm-storybook-cli#8]
Hey, 

I can't seem to get this to work using a monorepo using lerna. 

> DSM =>    Package @storybook/addon-a11y was not found in node_modules directory. Try running "npm install".
DSM =>    Package @storybook/addon-actions was not found in node_modules directory. Try running "npm install".
DSM =>    Package @storybook/addon-console was not found in node_modules directory. Try running "npm install".
DSM =>    Package @storybook/addon-links was not found in node_modules directory. Try running "npm install".
DSM =>    Package @storybook/addon-options was not found in node_modules directory. Try running "npm install".
DSM =>    Package @storybook/addon-storysource was not found in node_modules directory. Try running "npm install".
DSM =>    Package @storybook/addon-viewport was not found in node_modules directory. Try running "npm install".
DSM =>    Package @storybook/react was not found in node_modules directory. Try running "npm install".
DSM =>    Custom prettier configuration was not found for this project
DSM =>  ✖ TypeError: Invalid Version: ^5.2.8`

In a Monorepo the node modules live outside the packages folder. Any idea on the issue? FYI, storybook does run locally without using anything DSM related.

Regards,
Liam

**Comment by petermikitsh** [comment]
If you're using a monorepo managed with yarn workspaces, packages are sometimes hoisted, and that can create problems with this module. The workaround is to add the following `workspaces.nohoist` config to your root package.json:

```json
{
  "name": "monorepo-rooot",
  "private": true,
  "workspaces": {
    "nohoist": [
      "**/@storybook/**",
      "**/@invisionapp/dsm-storybook/**"
    ]
  }
}
```
